# Generated by Django 6.0.4 on 2026-05-22 13:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('customer', 'Customer (Seeker)'), ('landlord', 'Landlord (Owner)'), ('manager', 'General Manager / Admin')], default='customer', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be valid Ugandan format: '07XXXXXXXX' or '+2567XXXXXXXX'.", regex='^\\+?256\\d{9}$|^0\\d{9}$')])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_number', models.CharField(blank=True, help_text='National ID Number (NIN)', max_length=20, null=True, unique=True)),
                ('national_id_front', models.ImageField(blank=True, help_text='Upload the front of your national ID', upload_to='listings/national_ids/')),
                ('national_id_back', models.ImageField(blank=True, help_text='Upload the back of your national ID', upload_to='listings/national_ids/')),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=20)),
                ('verification_requested_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landlord Profile',
                'verbose_name_plural': 'Landlord Profiles',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title (e.g. Spacious Self-contained in Wandegeya)', max_length=200)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('self_contained', 'Self-contained Room')], default='single', max_length=20)),
                ('price_per_month', models.PositiveIntegerField(help_text='Rent price per month in UGX')),
                ('location', models.CharField(help_text='Exact location (e.g. Wandegeya, Kampala)', max_length=255)),
                ('telephone', models.CharField(help_text='Contact telephone number (e.g. +256789000000)', max_length=20)),
                ('image_front', models.ImageField(help_text='Front view of the house', upload_to='listings/images/')),
                ('image_inside', models.ImageField(help_text='Inside view of the room', upload_to='listings/images/')),
                ('image_other', models.ImageField(help_text='Any other view (e.g. compound or bathroom)', upload_to='listings/images/')),
                ('description', models.TextField(help_text='Detailed description of the house')),
                ('in_gate', models.BooleanField(default=False, verbose_name='Located inside a gate')),
                ('inner_bathroom', models.BooleanField(default=False, verbose_name='Has inner bathroom')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_taken', models.BooleanField(default=False, verbose_name='Marked as taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Your full name', max_length=100)),
                ('sender_email', models.EmailField(help_text='Your email address', max_length=254)),
                ('sender_phone', models.CharField(help_text='Your phone number', max_length=20)),
                ('offered_price', models.PositiveIntegerField(blank=True, help_text='Price customer is willing to pay (optional)', null=True)),
                ('message_text', models.TextField(help_text='Your message to the landlord')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read by landlord')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landlord_response_sent', models.BooleanField(default=False, verbose_name='Landlord responded')),
                ('response_method', models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email & WhatsApp')], max_length=20, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing')),
                ('sender', models.ForeignKey(blank=True, help_text='Registered user sender tracking link (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Message',
                'verbose_name_plural': 'Customer Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
