# Generated by Django 6.0.4 on 2026-05-20 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title (e.g. Spacious Self-contained in Wandegeya)', max_length=200)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('self_contained', 'Self-contained Room')], default='single', max_length=20)),
                ('price_per_month', models.PositiveIntegerField(help_text='Rent price per month in UGX')),
                ('location', models.CharField(help_text='Exact location (e.g. Wandegeya, Kampala)', max_length=255)),
                ('telephone', models.CharField(help_text='Contact telephone number (e.g. +256789000000)', max_length=20)),
                ('image_front', models.ImageField(help_text='Front view of the house', upload_to='listings/images/')),
                ('image_inside', models.ImageField(help_text='Inside view of the room', upload_to='listings/images/')),
                ('image_other', models.ImageField(help_text='Any other view (e.g. compound or bathroom)', upload_to='listings/images/')),
                ('description', models.TextField(help_text='Detailed description of the house')),
                ('in_gate', models.BooleanField(default=False, verbose_name='Located inside a gate')),
                ('inner_bathroom', models.BooleanField(default=False, verbose_name='Has inner bathroom')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
