# Generated by Django 6.0.4 on 2026-05-20 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_landlordprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Your full name', max_length=100)),
                ('sender_email', models.EmailField(help_text='Your email address', max_length=254)),
                ('sender_phone', models.CharField(help_text='Your phone number', max_length=20)),
                ('message_text', models.TextField(help_text='Your message to the landlord')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
