# Generated by Django 6.0.4 on 2026-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='offered_price',
            field=models.PositiveIntegerField(blank=True, help_text='Price customer is willing to pay (optional)', null=True),
        ),
    ]
